### PR TITLE
Added delta feature calculation function; also updated test example

### PR DESCRIPTION
**Pull request by ybdarrenwang**

### CODE REVIEW

**Comment by mr-wednesday** [comment]
Hello, after the denominator fix the result returns vectors with -inf for all frames.

**Comment by philipperemy** [comment]
@jameslyons can you have a look at this one please?

**Comment by philipperemy** [comment]
@ybdarrenwang please have more than one change set. Focus on Delta first. Be careful about the format of your tabs. Thanks!

**Comment by philipperemy** [comment]
And check your calculations please. I did my own implementation and we come with a different result!

**Comment by ybdarrenwang** [comment]
@philipperemy I cleaned up the tabs and removed changes except delta. Could you specify how my result is different from yours?

**Pull request merged**
